# -*- coding: utf-8 -*-
"""ML_Project_Lujain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15W_iR2Ayokp3d3JcfQzRhuVIyaB9Hyuz

#Heart Disease Risk Prediction Dataset

**1. Data loading**
"""


# Download latest version



import pandas as pd
df = pd.read_csv(path + '/heart_disease_risk_dataset_earlymed.csv')

df.head()
df.shape
df.info()
df.describe()

"""#2. Exploratory Data Analysis (EDA)"""

import seaborn as sns
import matplotlib.pyplot as plt


sns.countplot(x=df["Heart_Risk"])
plt.title("Distribution of heart risk")

print("\n ")

sns.boxplot(x="Heart_Risk", y="Age" , data=df)
plt.title("Age vs Heart Risk")

print("\n ")

sns.barplot(x="Heart_Risk", y="Chest_Pain", data=df)
plt.title("Relationship between chest pain & heart risk ")

print("\n ")

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(),cmap="coolwarm")

print("\n ")

"""#3. Data Cleaning"""

#check for missing value
df.isnull().sum()

#Data has no missing values to replce it.

#check for duplicates value
print("No. of duplicated value :",df.duplicated().sum())

df.drop_duplicates()

print("Data has 6245 duplicates value , so I drop it")

#check for outliers
for col in df.columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR


    outliers= df[(df[col]<lower) | (df[col]>upper)]

    print(col, ":" , len(outliers))


print("\nOutliers were analyzed using IQR method.There is no outliers detected,\nso no need to removal. ")

"""#4. Preprocessing"""

#Split features

X = df.drop("Heart_Risk", axis=1)
y = df["Heart_Risk"]

#Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled= scaler.fit_transform(X)

"""Scaling applied to encure fair contribuation of all features.

#5. Dimensionality Reduction (PCA)
"""

from sklearn.decomposition import PCA

pca = PCA()
X_pca= pca.fit_transform(X_scaled)

import numpy as np

explained_variance =  np.cumsum(pca.explained_variance_ratio_)
print(explained_variance)

plt.plot(explained_variance)
plt.xlabel("Number of components")
plt.ylabel("explained_variance")
plt.title("PCA explained variance")
plt.show()

pca = PCA(n_components=0.93)
X_pca = pca.fit_transform(X_scaled)

#Before and after PCA
print("Before PCA :",X_scaled.shape)
print("After PCA  :", X_pca.shape)

"""The number of n_components was selected based on explained_variance ratio.Threshold of 93% is chosen to retain most of the info, reducing number of dimensionalty and improve efficiency.
The original dataset contained 18 features, so PCA provided only small reduction.

#6.Modeling
"""

from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(
    X_pca,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y #stratify=y preserve classification ratio
)

from sklearn.linear_model import LogisticRegression


lr=LogisticRegression(random_state=42)
lr.fit(X_train , y_train)

y_pred_lr= lr.predict(X_test)

"""#7.Evaluation"""

from sklearn.metrics import accuracy_score , classification_report

print("Accuracy :", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

from sklearn.metrics import confusion_matrix

cm= confusion_matrix(y_test, y_pred_lr)
plt.figure(figsize=(5,4))
sns.heatmap(cm , annot=True , fmt='d' , cmap='Blues')
plt.title("Logistic Regression Confusion Matrix")
plt.show()

from sklearn.ensemble import RandomForestClassifier

rf= RandomForestClassifier(random_state=42)
rf.fit(X_train,y_train)

y_pred_rf = rf.predict(X_test)

print("Accuracy", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

cm= confusion_matrix(y_test, y_pred_rf)
plt.figure(figsize=(5,4))
sns.heatmap(cm , annot=True , fmt='d' , cmap='Blues')
plt.title("Random Forest Confusion Matrix")
plt.show()

"""#8.**Conclusion**

#9.**Stremlit**
"""


# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import seaborn as sns
# import matplotlib.pyplot as plt
# 
# from sklearn.preprocessing import StandardScaler
# from sklearn.decomposition import PCA
# from sklearn.ensemble import RandomForestClassifier
# 
# # =========================
# # PAGE CONFIG
# # =========================
# st.set_page_config(
#     page_title="Heart Risk AI Dashboard",
#     page_icon="❤️",
#     layout="wide"
# )
# 
# # =========================
# # CUSTOM STYLE (A+ DESIGN)
# # =========================
# st.markdown("""
# <style>
# body {
#     background-color: white;
# }
# h1, h2, h3 {
#     color: #C1121F;
# }
# .stMetric {
#     background-color: #fff5f5;
#     border-radius: 10px;
#     padding: 10px;
# }
# .stButton>button {
#     background-color: #C1121F;
#     color: white;
#     border-radius: 8px;
#     height: 3em;
# }
# .stButton>button:hover {
#     background-color: #8B0000;
#     color: white;
# }
# </style>
# """, unsafe_allow_html=True)
# 
# # =========================
# # TITLE
# # =========================
# st.title("❤️ Heart Disease Risk Prediction Dashboard")
# st.caption("AI-powered medical risk prediction system (Machine Learning Project)")
# 
# # =========================
# # LOAD DATA
# # =========================
# @st.cache_data
# def load_data():
#     df = pd.read_csv("your_dataset.csv")  # غيّر المسار
#     return df
# 
# df = load_data()
# 
# # =========================
# # PREPROCESSING (ONCE)
# # =========================
# X = df.drop("Heart_Risk", axis=1)
# y = df["Heart_Risk"]
# 
# scaler = StandardScaler()
# X_scaled = scaler.fit_transform(X)
# 
# pca = PCA(n_components=0.90)
# X_pca = pca.fit_transform(X_scaled)
# 
# model = RandomForestClassifier(random_state=42)
# model.fit(X_pca, y)
# 
# # =========================
# # SIDEBAR MENU
# # =========================
# menu = st.sidebar.radio(
#     "Navigation",
#     ["🏠 Overview", "📊 EDA", "🧠 Prediction"]
# )
# 
# # =========================
# # OVERVIEW PAGE (A+ KPIs)
# # =========================
# if menu == "🏠 Overview":
# 
#     st.header("Dataset Overview")
# 
#     col1, col2, col3 = st.columns(3)
# 
#     col1.metric("Total Records", df.shape[0])
#     col2.metric("Features", df.shape[1]-1)
#     col3.metric("Risk Cases", int(df["Heart_Risk"].sum()))
# 
#     st.write("### Sample Data")
#     st.dataframe(df.head())
# 
#     st.write("### Target Distribution")
# 
#     fig, ax = plt.subplots()
#     sns.countplot(x=df["Heart_Risk"], palette=["#C1121F", "#FFB3B3"], ax=ax)
#     st.pyplot(fig)
# 
# # =========================
# # EDA PAGE (PRO VISUALS)
# # =========================
# elif menu == "📊 EDA":
# 
#     st.header("Exploratory Data Analysis")
# 
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         st.subheader("Correlation Heatmap")
#         fig, ax = plt.subplots(figsize=(6,4))
#         sns.heatmap(df.corr(), cmap="Reds", ax=ax)
#         st.pyplot(fig)
# 
#     with col2:
#         st.subheader("Age Distribution")
#         fig, ax = plt.subplots()
#         sns.histplot(df["Age"], bins=30, kde=True, color="#C1121F", ax=ax)
#         st.pyplot(fig)
# 
#     st.subheader("Heart Risk vs Chest Pain")
#     fig, ax = plt.subplots()
#     sns.barplot(x="Heart_Risk", y="Chest_Pain", data=df, palette=["#C1121F", "#FFB3B3"], ax=ax)
#     st.pyplot(fig)
# 
# # =========================
# # PREDICTION PAGE (A+ UX)
# # =========================
# elif menu == "🧠 Prediction":
# 
#     st.header("Heart Disease Risk Prediction")
# 
#     st.write("Enter patient details below:")
# 
#     inputs = []
# 
#     cols = st.columns(2)
# 
#     for i, col in enumerate(X.columns):
#         with cols[i % 2]:
#             val = st.number_input(col, value=float(X[col].mean()))
#             inputs.append(val)
# 
#     if st.button("Predict Risk ❤️"):
# 
#         input_array = np.array(inputs).reshape(1, -1)
#         input_scaled = scaler.transform(input_array)
#         input_pca = pca.transform(input_scaled)
# 
#         prediction = model.predict(input_pca)[0]
#         prob = model.predict_proba(input_pca)[0][1]
# 
#         st.subheader("Result")
# 
#         if prediction == 1:
#             st.error(f"⚠ High Risk of Heart Disease ({prob:.2%})")
#             st.write("Recommendation: Consult a doctor for further examination.")
#         else:
#             st.success(f"✅ Low Risk of Heart Disease ({prob:.2%})")
#             st.write("Maintain a healthy lifestyle.")



# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# streamlit
# pands

df = pd.read_csv("heart_disease_risk_dataset_earlymed.csv")
